version: "3.8"

services:
  gateway:
    build: ./gateway
    hostname: gateway
    ports:
      - "8080:8080"
    networks:
      - net
    restart: unless-stopped

  middleware:
    build:
      context: ./middleware
      dockerfile: Dockerfile
    restart: unless-stopped

  web_scraper:
    build: ./web_scraper
    hostname: web_scraper
    networks:
      - net
    restart: unless-stopped

  manager_ollama:
    build: ./manager_ollama
    container_name: manager-ollama
    hostname: manager_ollama
    ports: 
      - "5001:5001"
    networks:
      - net
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    hostname: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - net
    restart: unless-stopped

volumes:
  cache:
    driver: local
  ollama_data:
    driver: local

networks:
  net:
    driver: bridge
