version: "3.8"

services:
  gateway:
    build: ./gateway
    hostname: gateway
    ports:
      - "8080:8080"
    networks:
      - net
    restart: unless-stopped

  middleware:
    build: ./middleware
    container_name: middleware
    hostname: middleware
    networks:
      - net
    restart: unless-stopped

  web-scraper:
    build: ./web_scraper
    container_name: web-scraper
    hostname: web_scraper
    networks:
      - net
    restart: unless-stopped

  manager-ollama:
    build: ./manager_ollama
    container_name: manager-ollama
    hostname: manager-ollama
    networks:
      - net
    restart: unless-stopped

  ollama:
    image: ollama/ollama
    container_name: ollama
    hostname: ollama
    volumes:
      - ollama_data:/root/.ollama
    networks:
      - net
    restart: unless-stopped
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9443
    volumes:
      - data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  ui:
    build: ./UI
    container_name: ui
    hostname: ui
    ports:
      - "80:80"
    networks:
      - net
    restart: unless-stopped

volumes:
  cache:
    driver: local
  ollama_data:
    driver: local
  data:

networks:
  net:
    driver: bridge
